sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2
notifications:
  slack:
    secure: "ENacikvjYr4DEMzPsV6p/UKqhwSl8FXdmlZFA2liJBnWNtWnEN/HNp24YTZNkPYm9/rCsdOdmQ1+6k1eXv/LWEzhzx/VteENGKMfjEfSuSSWNNAWJ3n+eME2dV1vnwvz8v3tl+QgYb142h0hdXEvK4G1aKsinOPFvTwxiwnJq4UcSxuKJP3O1RqXOFGm7EiEeyt83JSV4svphO2qiBfCEGTpY8ZIFtFGpJu06U+Au7baw2x/XdFrf+u+1zoOS/pusDBk8cPCXooKl1Ks+FvearhEV2inkgeQGBCkBs8PgNs0zyO2B1VamIaGSMPEia/YmS21fS3+BOhUB1hNAsIHoDjLQKAvkaZMSAZ61sP2wYSuolNcMmshY+gZaktZKRvM1VIkyHmxG0+DG6l9YhK6elG2jRB3yWW9z2PglEJntFLAs0CPrWWJgrSXlx3XUtYxoKWLXPFo/iIT3ztREaRyIaRqT9c1nxrpPBVrqpFI7GEBNT6i2IC6n4XUzkJ//jn1VY7B2+vYHkDnpZs5Wmcnu8bq+vSe/XkhrQd4gmJQ/SulN4pJuqxwZjXu28o3QteIE4NpnCG7rNHZkjqaBInNcrMez56puDB49b7w3my1hedVLk8ZNTfhvHYmbOsOt339Pgc/b73xvUfZjQh/iLC1ax/8ZEgI/nWPitw3mvYHIqs="
deploy:
  provider: rubygems
  gem: getto-roda
  on:
    tags: true
  api_key:
    secure: "kMzCWXDXI953tD0/SVlCRf393TvaLdVuoQTPP4OZAk7Ro+2w2Nzgjhck/z/EiWLOi4T0GNI2nLSOXEj4c1OuoA/CNsmLuWWkMCVRLWf2TwapDErb+7c6jtPLG/KKhq832E+QrgIyA6gNSjupl3Bahkz+X3RzYbuuuWOwwjq+RBW0Op1fnyKUNXaPb3xOgiM+iebE57pjzyp/tey5YFcQllZbNanpJLwY/xFMlJAePDAN42qdGbT2FaKyK8YxI/zzs6zqWconFwls2R1Y5WxghQRrNaSJqcHd3/j+bSF7Hk3Da9l+N/DN5pClyOSTLRUWRhpeY0dHNMlHHjM+isG0FlNVbmKdIQFaqWOq6f+iAlsbVGPWjVD1sTeRrXP7EF1Xu8VKEMkmL1wbuJf2CKJTODvpeGCQaxAt1dw1klPTHdjI2yg8F2Mhwxv1zG8nG+9kAzSmz4Iwx5x0n4d+6yEWn9McxOI2criokY0/hV53rlSCmVWBB0oIc7eqw69BVWsa/uFqdxp4bsW4rIqd3eEuidLJCbM1HnRacOgDTnH8Z876UVGPNCWAJ2vTsQS6bGIJzACbN3KenbTPMvWZkGnB0riRUX+DcRQYwDL+FmsXhbFTNHmNyERlrm5l41wB1uL2h0GB83xvRb/HYFXDb6sD1i/nxobbwjvTHFtCt/07t/0="
